### ISSUE TITLE
简体输入时emoji提示仍显示繁体

### ISSUE THREAD

**Issue by russell-liu** [rime/rime-cantonese#199]
@graphemecluster 最近嘅commit 0ce3764ce7d9d88f19620cb3e6f145125c1aeb99 修复咗繁简有差别时简体输入无法显示emoji嘅问题；呢个问题我最近都研究过，所以有以下提议：

目前修复后仲有一个小问题，就系简体输入时emoji提示仍显示繁体，如下图：
![1](https://github.com/user-attachments/assets/9acee671-32ae-43c2-b997-ef6b8f852773)

我觉得噉样有少少奇怪，谂到两个解决方法：

一，直程唔显示emoji旁嘅提示码。呢个系rime-emoji采用嘅解决方法（见： https://github.com/rime/rime-emoji/commit/618b9a5b8224b7742fb92398f8aecfed01b58b1b#diff-12665968d8ab35203380b57e071c87fe524e5cb970388dc04ad87372662b94e2R13 ；呢个commit删去咗emoji列表入面嘅简体字），只需加`tips: none`同`inherit_comment: false`。我觉得呢个方法嘅道理在于每个emoji候选项嘅前一个非emoji候选项其实等同佢嘅提示（如上图中`1. 妈妈`提示`2. 👩🏻️`），所以emoji隔嚟嘅提示码其实系多余嘅。

二，用比较另类嘅方法强行使emoji旁嘅提示码简体输入时显示为简体。将simplifier@emoji_suggestion摆系filters最前意味住用`tips: all`会显示繁体提示码，而提示码又唔可以再进行简化；所以我利用simplifier嘅`show_in_comment`功能，用多个simplifier「手动」产生简体提示码。噉样无可避免会产生重复嘅候选项，但好在用咗uniquifier就表面上冇分别。改动为：
```yaml
...

engine:
...
  filters:
    - simplifier@emoji_suggestion_duplicate
    - simplifier@simplified_variants_hk
    - simplifier@simplified_trad_tw
    - simplifier@simplified
    - simplifier@simplified_emoji_suggestion
    - simplifier@variants_hk
    - simplifier@trad_tw
    - simplifier
    - simplifier@emoji_suggestion
    - uniquifier
    - reverse_lookup_filter@jyut6ping3_reverse_lookup

...

emoji_suggestion_duplicate:
  opencc_config: emoji.json
  option_name: emoji_suggestion
  tips: none
  show_in_comment: true

simplified_variants_hk:
  option_name: variants_hk
  opencc_config: t2hkf.json
  tips: all
  show_in_comment: true
  comment_format:
    - xform/^/〔/
    - xform/$/〕/
  excluded_types: [ punct, phrase, user_phrase, table, user_table, completion, sentence ]

simplified_trad_tw:
  option_name: trad_tw
  opencc_config: t2tw.json
  tips: all
  show_in_comment: true
  comment_format:
    - xform/^/〔/
    - xform/$/〕/
  excluded_types: [ punct, phrase, user_phrase, table, user_table, completion, sentence ]

simplified:
  option_name: simplification
  opencc_config: t2s.json
  tips: all
  show_in_comment: true
  comment_format:
    - xform/^/〔/
    - xform/$/〕/
  excluded_types: [ punct, phrase, user_phrase, table, user_table, completion, sentence ]

simplified_emoji_suggestion:
  opencc_config: emoji.json
  option_name: emoji_suggestion
  tips: none
  excluded_types: [ punct, phrase, user_phrase, table, user_table, completion, sentence ]

...
```
呢个改动嘅弊处在于：复杂、冗长、效率低（uniquify前产生重复嘅候选项，尤其喺一词配多emoji时情况严重）。但佢确实可以实现简体输入时简体提示。

我个人觉得采纳方法一合理啲，但既然思考时将方法二谂咗出嚟，都写埋出嚟畀大家考虑同参考。
