### ISSUE TITLE
有幾個功能唔係好明

### ISSUE THREAD

**Issue by jmyz0455** [rime/rime-cantonese#26]
先多謝各位嘅辛勤付出，我好唔容易喺 macOS 用到一款粵拼輸入法 ;-P

我係跟住哩度離搞嘅：https://hanhngiox.net/install/mac.html ，入邊話有反查嘅功能，我又見到 *.dict.yaml 文件係有嘅啵，不過㩒 ` 掣又無反應。想問呢個功能要點用嘅
![](https://hanhngiox.net/install/mac/mac23.png)

同埋呢個 menu 入邊 2 3 8 9 項係乜意思，有咩用？
![](https://i.imgur.com/O6XdVE1.png)

哩個係我個配置：
```
patch:
  schema_list:
  - schema: jyut6ping3

  switcher:
    caption: 〔方案選單〕
    hotkeys:
    - Control+grave

  menu:
    page_size: 10
```

**Comment by laubonghaudoi** [comment]
我想問下，你部署嘅 dict 文件係唔係我哋而家呢個倉庫 rime-cantonese 嘅文件？你部署好晒我哋呢個倉庫嘅文件之後，可唔可以正常用粵拼打字？如果可以正常打字，噉冇理由冇得反查嘅。

**Comment by jmyz0455** [comment]
係你哋嘅文件，可以正常用粵拼打字。

我嘅流程係噉嘅，下載咗 Squirrel.pkg 兼安裝完之後，從你啲而家呢個倉庫 rime-cantonese 度 git clone 啲文件落嚟，將入面啲 *.dict.yaml 文件全部搬曬到 ~/Library/Rime 。然後根據條 [鏈接](https://hanhngiox.net/install/mac.html) 入面個 download.zip 語言包合集，齊係攞咗份 default.yaml 出嚟參考，無做過其它嘢，哩個係我嘅 ~/Library/Rime （jyut6ping3_ipa.schema.yaml 我刪咗因爲我只想用最標準嘅粵拼）：

```
ls -a ~/Library/Rime
.                             installation.yaml             jyut6ping3.userdb
..                            jyut6ping3.dict.yaml          luna_pinyin.userdb
.DS_Store                     jyut6ping3.lettered.dict.yaml stroke.userdb
build                         jyut6ping3.phrase.dict.yaml   user.yaml
default.yaml                  jyut6ping3.schema.yaml
```

係唔係要用緊其他輸入法然後再㩒 『`』 ？

**Comment by sgalal** [comment]
> 同埋呢個 menu 入邊 2 3 8 9 項係乜意思，有咩用？

<div lang="zh-HK">

3 同 8 就係控制半角/全角

中文/西文：用「西文」就淨系打英文，相當於㩒 <kbd>Shift</kbd>

🈶️️/🈚️️：是否啟用 Emoji 輸入

</div>

**Comment by sgalal** [comment]
<span lang="zh-HK">如果冇得用 luna_pinyin 反查，你試下直接用 luna_pinyin 可唔可以打字？如果可以，噉就應該可以反查嘅。</lang>

**Comment by laubonghaudoi** [comment]
你係咪連個`luna_pinyin`都刪埋？你如果要反查嗰嗰`luna_pinyin`都係必須嘅。

**Comment by jmyz0455** [comment]
@sgalal @laubonghaudoi 我已經加咗 `luna_pinyin` 喇，仲係唔得，切換到拼音打字就會咁。

![](https://i.ibb.co/mNKPy2Z/Snipaste-2020-03-31-12-22-47.png)

哩個係我最新嘅 default.custom.yaml 配置。

```
patch:
  schema_list:
  - schema: jyut6ping3
  - schema: luna_pinyin

  switcher:
    caption: 「切換」
    hotkeys:
    - Control+grave

  menu:
    page_size: 10
```
